feat: Add more notebook samples for documentation
Azure/mmlspark pull request #1043
Opened 2021-05-06 07:07 UTC by serena-ruan

2021-05-06 07:44 UTC, serena-ruan commented
/azp run

2021-05-06 08:49 UTC, serena-ruan commented
/azp run

2021-05-07 04:51 UTC, serena-ruan commented
/azp run

2021-05-07 04:53 UTC, serena-ruan commented
/azp run

2021-05-07 08:14 UTC, serena-ruan commented
/azp run

2021-05-11 03:00 UTC, serena-ruan commented
/azp run

2021-05-11 06:01 UTC, serena-ruan commented
/azp run

2021-05-11 06:56 UTC, serena-ruan commented
/azp run

2021-05-11 18:56 UTC, mhamilton723 commented on notebooks/samples/CognitiveServices - Celebrity Quote Analysis.ipynb
> +    "  .setUrl(\"https://api.bing.microsoft.com/v7.0/images/search\")\\\n",
You can remove this now

2021-05-11 19:42 UTC, imatiach-msft submitted a review, later dismissed

2021-05-11 19:43 UTC, mhamilton723 requested changes
Sent comments in teams

2021-05-11 20:09 UTC, eisber commented
For VW:

Advantages: you can also mention it supports distributed learning (the parallelization is controlled through the number of data partitions)
Quantile regression: I'd add a link to wikipedia or some nice blog article. One can do really interesting things w/ quantile regression (e.g. predict the 75% quantile of transportation cost)
maybe pull the boston sample up?

2021-05-12 07:29 UTC, serena-ruan commented on notebooks/samples/CognitiveServices - Celebrity Quote Analysis.ipynb
> +    "  .setUrl(\"https://api.bing.microsoft.com/v7.0/images/search\")\\\n",
Right! Done.

2021-05-12 07:52 UTC, serena-ruan commented
> For VW:
> 
> Advantages: you can also mention it supports distributed learning (the parallelization is controlled through the number of data partitions)
> Quantile regression: I'd add a link to wikipedia or some nice blog article. One can do really interesting things w/ quantile regression (e.g. predict the 75% quantile of transportation cost)
> maybe pull the boston sample up?

Done! Thanks for the comment!

2021-05-12 07:52 UTC, serena-ruan commented
/azp run

2021-05-12 10:31 UTC, serena-ruan commented
/azp run

2021-05-13 19:34 UTC, mhamilton723 requested changes
Great Job! Mostly just little things left.

Two larger questions:

 there are a lot of cache count and repartitions going on in VW code. Would you be able to try removing some of these to see if they are necessary? These operations in general will slow things down. 
 
 I will also send over Jack Gerrits example on Vowpal Wabbit Contextual Bandit code when available, (we don't have to block on this though it can be a separate PR)

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/Cognitive Services Overview.ipynb
> +    "### Web Search\n",
Web Search -> Search

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/Cognitive Services Overview.ipynb
> +    "- [Azure Cognitive search](https://docs.microsoft.com/en-us/azure/search/search-what-is-azure-search)\n"
Could you add corresponding scala snd python docs links?

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/LightGBM Overview.ipynb
> +    "train_data.show(10)"
Can remove

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/LightGBM Overview.ipynb
> +    "train_data.groupBy(\"Bankrupt?\").count().show()"
show -> display

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/LightGBM Overview.ipynb
> +    "model.saveNativeModel(\"/lgbmcmodel\")\n",
perhaps we can call this lgbmclassifier.model and add a cried markdown description that this allows you to extract the underlying lightGBM model for fast deployment after you train on spark

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/LightGBM Overview.ipynb
> +    "# plo\n",
typo: plo -> plot

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/LightGBM Overview.ipynb
> +    "    .withColumnRenamed('label', label_col)"
Can we save the result of this to parquet in the public blob then read it in so the demo is smaller?

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/LightGBM Overview.ipynb
> +    "dt2 = spark.read.format('csv').option('inferSchema', True) \\\n",
likewise here

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/Vowpal Wabbit Overview.ipynb
> +{
Nit to keep with the style of others lets make title Vowpal Wabbit - Overview. Likewise for other NBs

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/Vowpal Wabbit Overview.ipynb
> +    "train_data.groupBy(\"target\").count().show()"
display

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/Vowpal Wabbit Overview.ipynb
> +    "display(train.limit(10))"
no need for limit

2021-05-13 19:34 UTC, mhamilton723 commented on notebooks/samples/Vowpal Wabbit Overview.ipynb
> +    "display(prediction.limit(10))"
no need for limit

2021-05-14 07:03 UTC, serena-ruan commented
/azp run

2021-05-14 08:10 UTC, serena-ruan commented
/azp run

2021-05-17 05:15 UTC, serena-ruan commented
/azp run

2021-05-18 03:03 UTC, serena-ruan commented
/azp run

2021-05-19 06:29 UTC, serena-ruan commented
/azp run

2021-05-19 06:32 UTC, serena-ruan commented
/azp run

2021-05-19 07:14 UTC, merged